<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="Selection Tool">
    <text>Tool Shortcuts</text>
    <Action name="KisToolSelectTouch">
      <icon>tool_touch_selection</icon>
      <text>Selection Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Selection Tool</toolTip>
      <iconText>Selection Tool</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
