
install( FILES  
    Animation.kws
    Big_Paint.kws
    Big_Paint_2.kws
    Big_Vector.kws
    Default.kws
    Touch_Procreate_like.kws
    Touch_Procreate_like_Right.kws
    Small_Vector.kws
    Storyboarding.kws
    VFX_Paint.kws
    Minimal.kws
    DESTINATION ${KDE_INSTALL_DATADIR}/krita/workspaces)
